FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:stable-alpine AS production

#Copy build app
COPY --from=build /app/dist /usr/share/nginx/html

#Copy nginx config and SSL certs

COPY default.conf /etc/nginx/conf.d/default.conf
COPY ssl /etc/nginx/ssl

EXPOSE 443

CMD ["nginx","-g","daemon off;"]