## Blockchain Service DB StatefulSet / Service Deployement ##
#############################################################

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: blockchain-db
  labels:
    app: blockchain-db
spec:
  serviceName: "blockchain-db"
  replicas: 1
  selector:
    matchLabels:
      app: blockchain-db
  template:
    metadata:
      labels:
        app: blockchain-db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          envFrom:
          - secretRef:
              name: keplereum-k8s-secrets
  volumeClaimTemplates:
    - metadata:
        name: blockchain-db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-db-svc
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: blockchain-db

---

## Blockchain Service Deployement / K8s Service ##
############## Blockchain Service ################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-service
  labels:
    app: blockchain-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockchain-service
  template:
    metadata:
      labels:
        app: blockchain-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8091"
    spec:
      containers:
        - name: blockchain-service
          image: keplereum/blockchain-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8091
          envFrom:
          - secretRef:
              name: keplereum-k8s-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-service-svc
  labels:
    app: blockchain-service
spec:
  ports:
    - name: http  # ✅ IMPORTANT: Prometheus Operator needs this
      targetPort: 8091
      port: 80
  selector:
    app: blockchain-service
