package com.keplereum.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AlertAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlertAllPropertiesEquals(Alert expected, Alert actual) {
        assertAlertAutoGeneratedPropertiesEquals(expected, actual);
        assertAlertAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlertAllUpdatablePropertiesEquals(Alert expected, Alert actual) {
        assertAlertUpdatableFieldsEquals(expected, actual);
        assertAlertUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlertAutoGeneratedPropertiesEquals(Alert expected, Alert actual) {
        assertThat(actual)
            .as("Verify Alert auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlertUpdatableFieldsEquals(Alert expected, Alert actual) {
        assertThat(actual)
            .as("Verify Alert relevant properties")
            .satisfies(a -> assertThat(a.getAlertType()).as("check alertType").isEqualTo(expected.getAlertType()))
            .satisfies(a -> assertThat(a.getLatitude()).as("check latitude").isEqualTo(expected.getLatitude()))
            .satisfies(a -> assertThat(a.getLongitude()).as("check longitude").isEqualTo(expected.getLongitude()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlertUpdatableRelationshipsEquals(Alert expected, Alert actual) {
        // empty method
    }
}
